apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
  namespace: microservices
  labels:
    app: myapp
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
    - port: 80
      targetPort: 80
