apiVersion: v1
kind: Service
metadata:
  name: my_app-svc
  namespace: microservices
  labels:
    app: my_app
spec:
  type: NodePort
  selector:
    app: my_app
  ports:
    - port: 80
      targetPort: 80
